### ISSUE TITLE
Form without a name or key throws 'Cannot trigger a submit for a Form from within a different form'

### ISSUE THREAD

**Issue by rosskevin** [jquense/react-formal#107]
`Cannot trigger a submit for a Form from within a different form`

<img width="1007" alt="required_fields_-_dummy_com" src="https://cloud.githubusercontent.com/assets/136564/21523587/34623720-ccd5-11e6-87ce-b7da4fc0e1c6.png">

I neither provided a form `name` nor a form `key`.  Should a form work without a name or key specified?

**Comment by jquense** [comment]
yes its a bug. I have it fixed locally just need to push a release

**Comment by jquense** [comment]
fixed in `0.24.1`

**Comment by rosskevin** [comment]
Awesome, thanks for the support.
