### ISSUE TITLE
Example of array usage?

### ISSUE THREAD

**Issue by sotojuan** [jquense/react-formal#12]
I'm working on an application and react-formal is being very helpful. However, I'm curious on how to use an array schema.

The array part of the schema looks like this:

```javascript
  breakpoints: yup.array().of(yup.object({
    time: timeStr,
    action: yup.string()
  }))
```

It's an array of object with actions and the time to do them at. I'm having trouble figuring out how to access the fields or write them in React. I've tried using `breakpoints[0]`, `breakpoints[0].time`, etc and I get errors like "Can't find [0] of undefined" or "Cannot convert undefined or null to object".

I know this isn't a real issue but I wasn't sure where else to ask. It'd be great to have an example on how to use arrays either on the site (or in this issue so others can search)!

Thanks for the good work!

**Comment by jquense** [comment]
Hi there,

You are doing it correctly for the field name: `breakpoints[0].time` however if your form value has no value at that point it will try and select `breakpoints[0].time` but there will be no array to index at 0.

if you value looks something like: `{ breakpoints: [{ time:'12\12\2015'] }` it should work, but it won;t auto create array items for you (how would it know how many to make?)

**Comment by sotojuan** [comment]
Got it, my code is working now. Thanks a lot!

**Comment by jamesjjk** [comment]
@sotojuan I think I have the same issue, I'm dynamically adding elements to a form.. How did you resolve this?
