### ISSUE TITLE
Question: What are your thoughts on Formik?

### ISSUE THREAD

**Issue by danhayden** [jquense/react-formal#126]
First of all I'd like to say your work on React Formal has been incredible and I'd like to thank you for proving there's a much better way to manage forms in React. Also Yup is amazing (nice work!) and React Formal's integration is one of it's best features.

I have been using React Formal now for about 6 months and to date has been the only way to manage forms and validation in React that I have felt has the right abstraction and I have enjoyed using.

[Formik](https://github.com/jaredpalmer/formik) is a relatively new library but it is gaining a lot of attention recently. It appears on the surface to have a similar approach and goal to React Formal and also uses Yup for validation.

Formik also supports React Native which is a one area React Formal is lacking and I know this is unlikely to change. I'd be very interested to hear your thoughts on Formik and how you feel it compares to React Formal. Do you think it may be the successor to React Formal and perhaps the efforts combined?

Again thanks for all the work you've put in to your awesome OSS projects, you're a legend! 😄

**Comment by rosskevin** [comment]
Formik seems far more verbose, that's just my cursory thoughts.  Perhaps it's more raw to provide flexibility, but I've found react-formal to be both brief and able to handle everything I need.
