### ISSUE TITLE
Having Trouble using custom components

### ISSUE THREAD

**Issue by dannyphillips** [jquense/react-formal#13]
Trying to use my custom component `DropdownSelect` as a `Form.Field` (It's just a wrapper for your react-widget DropdownList component). When I add it to the markdown like this: 

``` <Form.Field type={DropdownSelect} /> ``` 

I get this error:

```Uncaught TypeError: Cannot read property '_currentElement' of null```

Am I using the `type` prop wrong?

**Comment by jquense** [comment]
that's the correct syntax, but Its a bit hard to debug it with jsut that. If you use `Form.addInputTypes('myselect', DropdownSelect)` and then set the type to `myselect` does it work. Also is DropdownSelect a class and not an Element?
