### ISSUE TITLE
Successive change doesn't appear to revalidate

### ISSUE THREAD

**Issue by rosskevin** [jquense/react-formal#131]
**Not sure if this is yup or react-formal issue**

```
email: string.required().email().uniqueOrSelf()
```

I'm expecting a re-validation will execute in the order added:
1. `string`
2. `required`
3. `email`
4. `uniqueOrSelf`

**When** a field is pre-filled with an email address
**And** I change it to an invalid email
**Then** I should expect an invalid email message (good so far)
**When** I `ctrl+a backspace`
**Then** the field is empty (still good)
**And** I should see an invalid required  message (problem here, still the previous message)

![profile_-_dummy_com](https://user-images.githubusercontent.com/136564/29320047-a550d042-819b-11e7-8985-d55da05c96aa.png)

![profile_-_dummy_com](https://user-images.githubusercontent.com/136564/29320019-955bb882-819b-11e7-99f7-8332d1a9b516.png)

![profile_-_dummy_com](https://user-images.githubusercontent.com/136564/29320037-9ed9a086-819b-11e7-8e20-2fd2a26a369f.png)

![profile_-_dummy_com](https://user-images.githubusercontent.com/136564/29320003-8d92e486-819b-11e7-8cb3-83534865607c.png)

---

I should note that this issue is present regardless of the order of invalid input.

**Comment by jquense** [comment]
I think this has to do with object key enumeration order. Can you confirm all the validations are actually run? My guess is that it's showing the first message in the hash and the `required` message, while first was added in later and now second.

**Comment by rosskevin** [comment]
That was a good theory, as I only display the first message.  

I just checked though and there should at least be the `required` error here, but only the `email` error:

![profile_-_dummy_com](https://user-images.githubusercontent.com/136564/29321994-b38f66a4-81a1-11e7-925c-09d6b955492a.png)

I'll see if all the validators get called.

**Comment by jquense** [comment]
if you can throw together a reprod in codesandbox i'll be happy to look as well

**Comment by rosskevin** [comment]
This seems to be working fine:
https://codesandbox.io/s/n47z5nxmjp

Closing as it doesn't seem to be caused by react-formal.

**Comment by rosskevin** [comment]
LOL, so the root cause of this is my over-optimization of my custom input's `shouldComponentUpdate`.  Debugging on `Form` `onValidate` proved that react-formal/yup are doing the right thing.
