### ISSUE TITLE
Can you elaborate more on type={MyDateInput}

### ISSUE THREAD

**Issue by lvdang** [jquense/react-formal#139]
How does Component: MyDateInput pass values back to the parent Component? In addition, how does the Parent pass the value to MyDateInput? Can you provide the complete code?

e.g.

<Form noValidate schema={modelSchema}>
  Use the schema to determine type
  <Form.Field
    name='dateOfBirth'
    placeholder='date'
  />

  Override it!
  <Form.Field
    name='dateOfBirth'
    type='time'
    placeholder='time only'
  />

  Use a custom Component
  (need native 'datetime' support to see it)
  <Form.Field
    name='dateOfBirth'
    type={MyDateInput}/>

</Form>

**Comment by jquense** [comment]
The field passes the value, an onChange handler, and a onBlur handler. You pass any value change back up by calling the onChange handler with the new value, like you would a controlled input. Take a look at the inputs source code here for more details
