### ISSUE TITLE
onSubmit not working

### ISSUE THREAD

**Issue by pcruz7** [jquense/react-formal#14]
Hi !

I'm trying to run a function after all the input fields are correctly set, but the onSubmit isn't being called. The render and function are as below:

```

registerAccount: function () {
    console.log(arguments);
},

...

<Form schema={userSchema} className="wrapper" method="post" action="/users/register" onSubmit={this.registerAccount}>
    <div className="row">
        <div className="column-12">
            <Field name="username" placeholder="Username" />
            <Message for="username" component={ErrorMessage} className="icon-notification" />
        </div>
    </div>
    <div className="row">
        <div className="column-12">
            <Field name="email" placeholder="Email" />
            <Message for="email" component={ErrorMessage} className="icon-notification"/>
        </div>
    </div>
    <div className="row">
        <div className="column-12">
            <Field type="password" name="password" placeholder="Password" />
            <Message for="password" component={ErrorMessage} className="icon-notification" />
        </div>
    </div>
    <div className="row">
        <div className="column-12">
            <Button className="btn">Register Account</Button>
        </div>
    </div>
</Form>

```

Is there something missing?

Thanks

**Comment by jquense** [comment]
You need a submit button I believe: `<Form.Button type='submit'/>`

**Comment by pcruz7** [comment]
that seems to break the validation itself, I've tried putting the onError callback and after validation it is called with an empty object as the first argument. Full component here: https://gist.github.com/pcruz7/ba1766692767a1a0b8b7

**Comment by jquense** [comment]
what do you mean it breaks the validation? Also what version are you using?

**Comment by pcruz7** [comment]
Validation doesn't run when using `<Button type="submit" />`. Using version 0.10.4

**Comment by pcruz7** [comment]
forget it @jquense ...there must've been something broken with my build. sorry for the bother, closing !

**Comment by jquense** [comment]
o great :) glad to hear it
