### ISSUE TITLE
How do I declare Yup data schema for type='checkbox' ?

### ISSUE THREAD

**Issue by lvdang** [jquense/react-formal#143]
//  Is this right?

this.customerSchema = yup
      .object({
          permissions: yup.array().required('Permission not checked').max(2),
        }),
      });

// 
 <Form.Field
          name="permissions"
          type="checkbox"
        />

        <Form.Field
          name="permissions"
          type="checkbox"
        />

**Comment by jquense** [comment]
usually for a checkbox you want `yup.bool()`

**Comment by lvdang** [comment]
How would I implement multiple checkbox for Form.Field name value?

e.g. yup schemas

this.customerSchema = yup
.object({
permissions: yup.object({
    green: yup.bool()
    yellow: yup.bool(),
    red: yup.bool(),
}),
});

//  How do I declare for multiple box name declaration?

<Form.Field name="permissions" type="checkbox"/>
  or 
<Form.Field name="permissions.green" type="checkbox"/>
<Form.Field name="permissions.yellow" type="checkbox"/>
<Form.Field name="permissions.red" type="checkbox"/>

**Comment by jquense** [comment]
For that I use the select list component in React widgets (react-formal-inputs) and an array for the schema

**Comment by tonilaukka** [comment]
I was looking for same example but couldn't find anser anywhere. Here is a working example. 
```
import React from "react";
import ReactDOM from "react-dom";
import Form from "react-formal";
import * as yup from "yup";
import { SelectList } from "react-widgets";

import "./styles.css";

const schema = yup.object({
  checkboxes: yup
    .array()
    .of(
      yup.object().shape({
        id: yup.string(),
        name: yup.string()
      })
    )
    .default([])
    .oneOf([true], "Must choose one")
});

class App extends React.Component {
  handleChange = form => {
    console.log(form);
  };

  handleError = error => {
    console.log(error);
  };

  handleSubmit = form => {
    console.log(form);
  };

  render() {
    return (
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
        <Form
          defaultValue={schema.default()}
          onChange={this.handleChange}
          onError={this.handleError}
          onSubmit={this.handleSubmit}
          schema={schema}
        >
          <SelectList
            data={[
              { id: "checkbox1", name: "Checkbox 1" },
              { id: "checkbox2", name: "Checkbox 2" },
              { id: "checkbox3", name: "Checkbox 3" }
            ]}
            onChange={this.handleChange}
            textField="name"
            name="checkboxes"
            multiple
          />
          <Form.Submit type="submit">Submit</Form.Submit>
        </Form>
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);```

Same on codesandbox: https://codesandbox.io/s/7z1q0rnq76

**Comment by lvdang** [comment]
thanks
    On Tuesday, April 9, 2019, 2:07:26 AM PDT, Toni Laukka <notifications@github.com> wrote:  
 
 
I was looking for same example but couldn't find anser anywhere. Here is a working example.
import React from "react";
import ReactDOM from "react-dom";
import Form from "react-formal";
import * as yup from "yup";
import { SelectList } from "react-widgets";

import "./styles.css";

const schema = yup.object({
  checkboxes: yup
    .array()
    .of(
      yup.object().shape({
        id: yup.string(),
        name: yup.string()
      })
    )
    .default([])
    .oneOf([true], "Must choose one")
});

class App extends React.Component {
  handleChange = form => {
    console.log(form);
  };

  handleError = error => {
    console.log(error);
  };

  handleSubmit = form => {
    console.log(form);
  };

  render() {
    return (
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
        <Form
          defaultValue={schema.default()}
          onChange={this.handleChange}
          onError={this.handleError}
          onSubmit={this.handleSubmit}
          schema={schema}
        >
          <SelectList
            data={[
              { id: "checkbox1", name: "Checkbox 1" },
              { id: "checkbox2", name: "Checkbox 2" },
              { id: "checkbox3", name: "Checkbox 3" }
            ]}
            onChange={this.handleChange}
            textField="name"
            name="checkboxes"
            multiple
          />
          <Form.Submit type="submit">Submit</Form.Submit>
        </Form>
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);```

Same on codesandbox: https://codesandbox.io/s/7z1q0rnq76

**Comment by MantasMikal** [comment]
@lvdang The example does not work. It always returns error on submit. I am not able to find working solution for multiple checkboxes. Or I am missing something?
@jquense

**Comment by user4302** [comment]
this worked for me,
i was validating each of these only if the other one did not have an input

```
step5ValidationSchema: {
//multiple checkboxes, multi select
    statement: Yup.array().when("plan", {
      is: (plan) => {
        return plan === undefined;
      },
      then: (schema) => schema.min(1, "This field is required"),
      otherwise: (schema) => schema.notRequired().optional().nullable(),
    }),
//multiple radio buttons, single select
    plan: Yup.string().when("statement", {
      is: (statement) => {
        return statement.length === 0;
      },
      then: (schema) => schema.required("This field is required"),
      otherwise: (schema) => schema.notRequired().optional().nullable(),
    }),
  },
```
