### ISSUE TITLE
StripUnknown as part of validate

### ISSUE THREAD

**Issue by racheldelman** [jquense/react-formal#157]
Is there a way to pass in options for yup.validate? I'd like to strip out all unknown properties when submitting my form, I see that form has an option for strict mode - is there something similar for stripping out unknown fields?

**Comment by racheldelman** [comment]
In the meantime I'm casting the values before submitting them like this:
`<Form
              onSubmit={values => {
              handleSubmit(schema.cast(values, { stripUnknown: true }));
            }}>`
but I was wondering if there was a better option

**Comment by jquense** [comment]
ya you can pass `stripUnknown` to the Form directly as a prop

**Comment by racheldelman** [comment]
thanks!
