### ISSUE TITLE
Uncaught TypeError: path.match is not a function when using Form onChange property

### ISSUE THREAD

**Issue by alextiley** [jquense/react-formal#16]
Hello,

Love the look of your form management component but having some problems getting it working with an onChange event.

Here's my class:

```javascript
import yup from 'yup';
import React from 'react';
import Form from 'react-formal';

class EmailForm extends React.Component {

    getSchema() {
        return yup.object({
            email: yup.string().email().default(this.props.email)
        });
    }

    getDefaultValues() {
        return this.getSchema().default();
    }

    render() {
        return (
            <Form
                schema={this.getSchema()}
                value={this.getDefaultValues()}
                onChange={model => this.setState({model})}>

                <Form.Field name="email" placeholder="Please enter an email address..." />
                <Form.Message for="email" />

                <Form.Button type="submit">Submit</Form.Button>
            </Form>
        );
    }
}

export default EmailForm;
```

Validation appears to work (the message shows and hides correctly and classes are correctly applied based on validity). However, I'm seeing the following in the console after every onChange event is fired: What am I doing wrong?

```javascript
Uncaught TypeError: path.match is not a function
    module.exports.forEach	@	index.js:42
    module.exports	@	reach.js:12
    (anonymous function)	@	Form.js:279
    Validator._validateField	@	Validator.js:49
    tryCallTwo	@	core.js:45
    doResolve	@	core.js:171
    Promise	@	core.js:65
    _validateField	@	Validator.js:48
    (anonymous function)	@	Validator.js:37
    validate	@	Validator.js:36
    (anonymous function)	@	Form.js:416
```

**Comment by alextiley** [comment]
It's worth noting that when I remove ```this.setState({model})``` I no longer get the error. However this does not meet my requirements as I need to be able to set state. Same thing happens if I swap ```this.setState({model})``` out with an action dispatch.

**Comment by jquense** [comment]
It all looks correct...It seems that `path` in this instance is undefined when it should be a string.

its a bit odd to use defaultValue with onChange, can you default the state.model to the default value, and then use `value={this.state.model }` instead of `defaultValue` and see if that helps? You should be able to do what you are doing but there may be a bad assumption somewhere on my part...other than that it would be helpful if you could step through the code at the error site to see what the values are since I can't repo this.

**Comment by alextiley** [comment]
Hi, thanks for getting back to me.

I initially started out with ```value``` because I'm wanting to use controlled inputs. It didn't work so changed to defaultValue (which is what you see copy and pasted above - forgot to change it back). Either way, both throw the same error.

It looks like ```path``` is in fact not undefined but in fact an object. When debugging line 12 of ```reach.js``` it seems to be passed a ```path``` of ```'postcode'``` twice, and then passed a ```path``` containing an event object, as below:

```
path: Object
args: Array[1]
event: "onChange"
fields: Array[1]
target: MessageTrigger
__proto__: Object
```
```

**Comment by jquense** [comment]
ok that's helpful, any chance you could let me know what the content of the event object is in this case? is it the onCHange event from the input?

**Comment by alextiley** [comment]
Got the above comment slightly wrong, the object is exactly as shown in my previous comment (not an actual event object). Here's a more expanded view of the object assigned to the ```path``` variable. Like you mentioned before, this should be a string but looks like it's accidentally passing this object through.

If it helps, I'm using the following versions:

react 0.13.3
react-formal 0.10.5
react-router 0.13.3
yup 0.9.2

```javascript
args: Array[1]
    0: "derr544rrrrgfded"
event: "onChange"
fields: Array[1]
    0: "postcode"
target: MessageTrigger
    _reactInternalInstance: ReactCompositeComponentWrapper
        _context: Object
            listen: listen(fn)
            messages: bound ()
            onFormSubmit: bound ()
            onValidateFields: onValidateFields(fields, event, target, args)
            onValidateGroup: onValidateGroup(group, event, target, args)
            register: register(names, group, target)
            registerWithForm: registerWithForm(listener)
            routeDepth: 2
            router: (props, context)
        _currentElement: ReactElement
            _context: Object
           _owner: ReactCompositeComponentWrapper
           _store: Object
           key: null
           props: Object
           active: false
           activeClass: "invalid-field"
           children: ReactElement
               _context: Object
               _owner: ReactCompositeComponentWrapper
               _store: Object
               key: null
               props: (...)
               ref: "input"
               type: _class()
           events: Array[2]
               0: "onChange"
               1: "onBlur"
           for: "postcode"
           group: undefined
           messages: Object
           options: Object
           __proto__: Object
           ref: null
           type: MessageTrigger()
        _instance: MessageTrigger
        _isOwnerNecessary: false
        _isTopLevel: false
        _mountImage: null
        _mountIndex: 0
        _mountOrder: 22
        _pendingCallbacks: null
        _pendingElement: null
        _pendingForceUpdate: false
        _pendingReplaceState: false
        _pendingStateQueue: null
        _renderedComponent: ReactCompositeComponentWrapper
        _rootNodeID: ".0.1.1.$=1$=010=20:0"
        _warnedAboutRefsInRender: false
    _unregister: ()
    context: Object
        onValidateFields: onValidateFields(fields, event, target, args)
        onValidateGroup: onValidateGroup(group, event, target, args)
        register: register(names, group, target)
    getDOMNode: (...)
    isMounted: (...)
    props: Object
        active: false
        activeClass: "invalid-field"
        children: ReactElement
        events: Array[2]
        for: "postcode"
        group: undefined
        messages: Object
        options: Object
    refs: Object
    state: null
```

**Comment by alextiley** [comment]
I've investigated some more by looking at the library code in more depth. I think I may know where it's going wrong but not 100% sure as I can't find a spec/test to describe how this should work.

In ```Form::componentWillReceiveProps``` there's a call to ```_queueValidation``` which passes an object containing fields. I think the return value of ```uniq((this._queue || []).concat(Object.keys(nextProps.errors || {})))``` is also returning an object containing fields, so the object being passed to _queueValidation incorrectly looks like:

```javascript
{
    fields: [
        {
            args: [], // containing field values
            event: "onChange",
            fields: [
                'email'
            ],
            target: MessageTrigger {}
        }
    ]
}
```

I think it should instead look like this:

```javascript
{
    fields: [
        'email'
    ]
}
```

It looks like it could be that uniq function that is the cause of the problem but like I say I'm not 100% sure. Hope that's of some use. If I get some time I'll try and see if I can fix myself but would be good to know if I'm going down the right path.

Thanks, Alex

**Comment by jquense** [comment]
I think you are right on target. the unique call should first pluck the fields property from anything in queue. I will fix it first thing but I'm traveling the next few days so if you want to PR it I'd happily accept

**Comment by alextiley** [comment]
Hi Jason,

I have this fixed on a local branch on my work laptop. Will get a pull request over to you sometime  tomorrow. It's a pretty simple fix, I just loop over all items in the queue and push their fields into a new array :) seems to do the trick. Thanks!

**Comment by alextiley** [comment]
Hi Jason,

I have this fixed on a local branch on my work laptop. Will get a pull request over to you sometime  tomorrow. It's a pretty simple fix, I just loop over all items in the queue and push their fields into a new array :) seems to do the trick. Thanks!

**Comment by alextiley** [comment]
I've created a pull request, let me know if it's working for you and you're happy. It does concern me that you couldn't reproduce but hopefully this fix works across the board. Had trouble writing tests for this and at the moment it's untested. It seems that the Form component is wrapped in some other component, which is making it completely untestable. Let me know if you have a suggested way around that.
