### ISSUE TITLE
submission handler dispatching when changing state

### ISSUE THREAD

**Issue by vendramini** [jquense/react-formal#165]
Good night.

I do have a form with a 'show password' button.
```javascript
const [passwordFieldType, setPasswordFieldType] = useState('password');
const onClickShowPass = () => setPasswordFieldType(passwordFieldType == 'password' ? 'text' : 'password');

<Formal
    schema={schema}
    className={'form-icons'}
    onSubmit={onSubmit}
>
//...form
    <button className={'show-password'} onClick={onClickShowPass}>Show password</button>
    <Button type={'submit'} className={'w-100'}>Login</Button>
</Formal>
```
When the state is changed, if the form is validated the `onSubmit` handler is fired.

Does this makes sense? I expected not to fire. If I click X times on 'show password', `onSubmit` is fired X times.

Thanks!

**Comment by jquense** [comment]
Hi there, It's expected b/c you don't have a `type` specified on the button, HTML defaults the type to `submit` in most cases, so it's actually acting like a submit button here. use `type='button'` instead

**Comment by vendramini** [comment]
omg... Thank you!
