### ISSUE TITLE
how to import default style

### ISSUE THREAD

**Issue by deezahyn** [jquense/react-formal#2]
Hi,

Is there a default theme included? Right now I get this:
http://take.ms/FcY9E

and it seems that date of birth requires react-widgets?  Classnames say 'rw-popup rw-widget'.

I'm using webpack and using commonjs syntax.

**Comment by jquense** [comment]
yup there is a default stylesheet that comes with react-widgets, which is what `react-formal-inputs` uses. You can check out the complete docs here: http://jquense.github.io/react-widgets/docs/#/ but quickly you want to either include the stylesheet in `/react-widgets/dist/css/react-widgets.css` in your html file directly, or if you want to require() it using webpack you can with: `require('react-widgets/dist/css/react-widgets.css')`

**Comment by deezahyn** [comment]
okay that works! :)
