### ISSUE TITLE
The package react@0.14.0 does not satisfy its siblings' peerDependencies requirements

### ISSUE THREAD

**Issue by nickuraltsev** [jquense/react-formal#21]
`npm install` fails with EPEERINVALID error now:

```
npm ERR! peerinvalid The package react@0.14.0 does not satisfy its siblings' peerDependencies requirements! 
```

Looks like the problem is that react-formal depends on react-router 0.13.x which has react 0.13.x as a peer dependency. 

After removing component-playground (which has react 0.14.x as a peer dep) from dependencies, I got a more detailed error message:

 ```
npm ERR! peerinvalid The package react@0.14.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-input-message@0.7.2 wants react@>=0.13.0 || ^0.14.0-beta1
npm ERR! peerinvalid Peer uncontrollable@3.1.3 wants react@>=0.11.0
npm ERR! peerinvalid Peer react-formal-inputs@1.0.0 wants react@>=0.11.0
npm ERR! peerinvalid Peer react-testutil-query@1.0.0 wants react@>=0.13.0
npm ERR! peerinvalid Peer react-router@0.13.4 wants react@0.13.x
```

Changing react-router version to ^1.0.0-rc1 seems to fix the issue.

**Comment by jquense** [comment]
React-formal only depends on react -router as a devDependency, it shouldn't affect your use or installing of the module normally. It looks like you are using react-router with a version of react that isn't compatible

**Comment by nickuraltsev** [comment]
Right, the issue is with dev installation. I should have been more specific.

**Comment by nickuraltsev** [comment]
React 0.14.0 was released yesterday, hence this conflict.

**Comment by jquense** [comment]
updated
