### ISSUE TITLE
Cross-field validations?

### ISSUE THREAD

**Issue by saikat** [jquense/react-formal#24]
Apologies if this is already covered somewhere, but what is the best way with react-formal to do validations that depend on the values of multiple fields?  Should I just hook into the form's onChange handler and set this.setState with the errors?

**Comment by saikat** [comment]
Oh I see that perhaps the way to do this is to add a .test to the object schema.  So something like this perhaps?

var modelSchema = yup.object({
    password: string.required('Please enter a password'),
    confirmPassword: string.required('Please confirm your password'),
  }).test('passwords-match', 'Passwords do not match', value => value.password === value.confirmPassword);

**Comment by jquense** [comment]
There are a few ways to handle it depending on your needs, you can do it like you have it above: adding the validation to the parent. Or (what I generally do) add it to both and use the `.parent` value in the test function.

```js
function samePassword() {
  let parent = this.parent;

  return  parent.password === parent.confirmPassword
}

var modelSchema = yup.object({
  password: string
    .required('Please enter a password')
    .test('passwords-match', 'Passwords do not match', samePassword)
  confirmPassword: string
     .required('Please confirm your password')
     .test('passwords-match', 'Passwords do not match', samePassword)
})
```


further reading: https://github.com/jquense/yup#mixedteststring-name-string-message-function-fn-bool-callbackstyleasync

**Comment by saikat** [comment]
Thank you, that's very helpful.  Closing this.
