### ISSUE TITLE
onSubmit handler called even if there are validation errors

### ISSUE THREAD

**Issue by saikat** [jquense/react-formal#26]
I believe the issue is that this code:

https://github.com/jquense/react-formal/blob/master/src/Form.jsx#L397

is expecting the the validate method to throw an error, but I believe the method actually returns errors.

**Comment by jquense** [comment]
hi there!

Are you sure the form has errors? The `validate()` definitely _does_ throw the validation errors so that line is correct, I make use of the onSubmit handler fairly often in my own code and it hasn't exhibited that behavior

**Comment by saikat** [comment]
I'll try to set up a minimal reproduction.  Thanks for the quick reply!
