### ISSUE TITLE
E-mail validation runs too quickly, before form field is even blurred

### ISSUE THREAD

**Issue by saikat** [jquense/react-formal#28]
Here's a video of it in action.  Will try to add some code to the issue, but it's a pretty minimal form.

https://www.dropbox.com/s/y3omi5wakez2d70/react-formal-email-validation.mov?dl=0

**Comment by jquense** [comment]
hi there, fields validate onChange by default. make sure to only validate onBlur and not onChange via the events prop on the field if that's what you want.

**Comment by saikat** [comment]
Thanks!
