### ISSUE TITLE
Dynamically adding form elements (array)

### ISSUE THREAD

**Issue by jamesjjk** [jquense/react-formal#29]
I would like to dynamically add form elements. I have tried combinations of validation:
let someModelSchema = yup.object({ group: yup.array().of(yup.object({itemA: yup().number(), itemB: yup().number()})) });

However I assumed that the correct naming convention would be (name attr) 'group.itemA' for the relevant number input or 'group[0].itemA' neither of which seem to work. Any advice on how to dynamically add form elements and validate these elements? Thanks!

**Comment by jquense** [comment]
The right path would be `'group[0].itemA'` and generally if you do update something at that path react-formal will go ahead and create the item at that index if it doesn't exist. However you generally want to handle the creation of these new items yourself. To do that just insert a new item in your list and rerender your form.

**Comment by jamesjjk** [comment]
Great thanks for the tip it works nicely just need to ensure the key is always unique when re-rendering
