### ISSUE TITLE
How to set invalid date message, use onsubmit and re-render form

### ISSUE THREAD

**Issue by deezahyn** [jquense/react-formal#3]
1. How do I set the invalid date message for `type=date` . Right now if I choose a date, and remove it, I get: ``this (value: ` `) must be a `date` type``

2. If I only want to update my models onSubmit?
  `<Form
            schema={modelSchema}
            defaultValue={modelSchema.default() }
            onSubmit={ model => this.setState({ model })}
          >`

  If I do this:
  `
   componentDidUpdate(prevProps, prevState) {
    console.log(this.state.model)
  }
 `
I only get a SyntheticEvent Object; This works correctly if I use onChange however.

3. How do I force re-render the whole form on schema change? Say if I want to customize the messages.

4. Is there an example how to use errors object?

**Comment by jquense** [comment]
1. you can change the type error message with [`dateSchema.typeError(message)`](https://github.com/jquense/yup#mixedtypeerrormessage-default-path-value-value-must-be-a-type-type), if you want to allow "empty" values then you can set `.nullable()` on your schema so you won;t get that error if it is null (or set it to `undefined`)

2. `onSubmit` doesn't pass the value back only the submit event object, if you want to persist changes onSubmit do something like:
  ```jsx
render(){
  return (
   <Form 
     value={this.state.model} 
     onChange={model => this.setState({ model })}
     onSubmit={()=> saveModelSomewhere(this.state.model)}>
      {/* fields omitted */}
   </Form>)
}
   ```
3. you can "control" the errors like you can the value, so you can listen for validations via `onError` and then update the `errors` prop
```jsx
render() {
  return (
   <Form 
     errors={this.state.errors} 
     onError={ errors => this.setState({ errors })}>
      {/* fields omitted */}
      <button onClick={this.clearErrors) type='button'/>clear errors</button>
   </Form>)
}

clearErrors(){
  this.setState({ errors: {} })
}
```
Now if you update the `errors` state it will trigger a render of the entire form with the new errors

**Comment by deezahyn** [comment]
trying no. 1
```
var modelSchema = yup.object({

    name: yup.object({
      first: defaultStr.required('please enter a first name'),
      last:  defaultStr.required('please enter a surname'),
    }),

    dateOfBirth: yup.date()
      .max(new Date(), "You can't be born in the future!"),

    colorId: yup.number().nullable()
      .required('Please select a color')
  });


let objectErrors ={
 "name.first": [
   'First names are required',
   'Names must be at least 2 characters long'
 ],
}


modelSchema.dateOfBirth.typeError('testing');
```

I get `Uncaught TypeError: Cannot read property 'typeError' `

**Comment by deezahyn** [comment]
on no. 3
Given the schema I have on top, how would I override say dateOfBirth and colorId error message?

**Comment by jquense** [comment]
That's not how the schema objects work, there isn't just a property `dateOfBirth` on the modelSchema. you can either do this:

```js
var modelSchema = yup.object({

    name: yup.object({
      first: defaultStr.required('please enter a first name'),
      last:  defaultStr.required('please enter a surname'),
    }),

    dateOfBirth: yup.date()
      .max(new Date(), "You can't be born in the future!")
      .typeError('testing'),
})
````

Or if you want to "update" the schema later you need to do something like

```js
var dob = yup.date().max(new Date(), "You can't be born in the future!");

var modelSchema = yup.object({

    name: yup.object({
      first: defaultStr.required('please enter a first name'),
      last:  defaultStr.required('please enter a surname'),
    }),

    dateOfBirth: dob,
  });

// shape works like _.extend or Object.assign()
modelSchema.shape({
  dateOfBirth: dob.typeError('testing')
})
```

Addendum to number 3, if you update the schema prop on the form, it should rerender the entire form, however it won't re-validate fields in error, that Is probably a good idea tho, I will add it in the next version...

**Comment by deezahyn** [comment]
I see, so basically errors object is the current error of the form returned by validation? Sorry was confused, I thought error object is used to add custom validation.

using this
```
modelSchema.shape({
  dateOfBirth: dob.typeError('testing')
})
```

Is there an api for force validation of the form?

**Comment by jquense** [comment]
> I see, so basically errors object is the current error of the form returned by validation? Sorry was confused, I thought error object is used to add custom validation.

Right the `errors` object is the error state of the form, any error in that object will get displayed by the form provided there is a matching `Message` component for the error field. The `errors` object is a Map of field names (paths) to errors for those fields.

```js
var errors = {
  'dateOfBirth': ['hey! please enter this'] 
}
```
You can do whatever you like to the error object, replace messages, remove certain ones, etc. Its up to you, but the default behavior is just to pass on the yup schema error message and display that.

There isn't a direct API for re-validating a form (aside from clicking on a `<Form.Button/>` however you can just validate the model yourself, like the way the onSubmit code works. Ideally there should be a proper API for this but in the meantime, you can do this:

```js
render() {
  return (
   <Form 
     errors={this.state.errors} 
     onError={ errors => this.setState({ errors })}>
      {/* fields omitted */}
   </Form>)
}

validateForm(){
  modelSchema
      .validate(this.state.model, { strict: true, abortEarly: false })
      .catch(err => {
        // this turns an array of ValidationErrors into an object hash
        var errors = err.inner.reduce((list, error) => {
          if ( !list[error.path]) list[error.path] = []

          list[error.path] = list[error.path].concat(error.errors)

          return list
        }, {})

        this.setState({ errors })
      })
}
```

and relevant yup documentation: https://github.com/jquense/yup#validationerror

**Comment by deezahyn** [comment]
also how can I use dropdownlist instead of select?

```
            <DropdownList
              valueField='id' textField='name'
              data={ colors }
              defaultValue={ 1 }
              name='colorId'
            />
```

**Comment by jquense** [comment]
```js
<Form.Field 
  type='dropdownlist'
  valueField='id' 
  textField='name'
  data={ colors }
  name='colorId'
/>
```
see the full list here: https://github.com/jquense/react-formal-inputs, alternatively you can set `type` to any React Component like `<Form.Field type={DropdownList}/>` the string name is just a convenience.

`defaultValue` won't work in this case because the field is manually setting value/onChange on the inputs, To set an initial value for a field initialize the form value:

```js
<Form value={{ colorId: 1 }}/>

// or set the schema default
colorId: yup.number()
  .nullable()
  .default(1)
  .required('Please select a color')

//and then 
modelSchema.default() //=> { colorID: 1 }
```

**Comment by deezahyn** [comment]
>You can do whatever you like to the error object, replace messages, remove certain ones, etc. Its up   to you, but the default behavior is just to pass on the yup schema error message and display that.

Does that mean if I change the error message object I can override what's display say `Form.Message for={'name'} />` ?

**Comment by jquense** [comment]
> Does that mean if I change the error message object I can override what's display say `Form.Message for={'name'} />` ?

sure, tho I generally recommend that you just set the message you want in the schema itself, but you can do whatever you like :). It is probably easier to mess with the `errors` object if the message if very dynamic

```js
render() {
  return (
   <Form 
     errors={this.state.errors} 
     onError={this.setErrors}>
      {/* fields omitted */}
   </Form>)
}

setErrors(errors) {
  if ( errors['dateOfBirth'] ) //if dob is in the error state change the message
    errors['dateOfBirth'] = "swap out the message for this one!"

  this.setState({ errors })
}

```

**Comment by deezahyn** [comment]
Doesn't work http://take.ms/01Pr5

Seems like valueField isn't working :(

```
render() {
    var colors = [
      { id: 0, name: 'orange'},
      { id: 1, name: 'purple'},
      { id: 2, name: 'red' },
      { id: 3, name: 'blue' },
    ];
    return (
      <div>
          <Form
            schema       = { modelSchema }
            defaultValue = { modelSchema.default() }
            onError      = { errors => this.setState( { errors }) }
            onChange     = { model => this.setState( { model } ) }
          >
            <div>
              <label>Name</label>

              <Form.Field name='name.first' placeholder='First name' className='form-control' />
              <Form.Message for={'name.first'} />

              <Form.Field name='name.last' placeholder='Surname' className='form-control' />

              <Form.Message for={'name.last'} />
            </div>

            <label>Date of Birth</label>
            <Form.Field name='dateOfBirth' />
            <Form.Message for='dateOfBirth' />

            <label>Favorite Color</label>
            <Form.Field
              type='dropdownlist'
              valueField='id'
              textField='name'
              data={ colors }
              name='colorId'
              defaultValue={ 1 }
            />
            <Form.Message for='colorId'/>
          <Form.Button type='submit'>Submit</Form.Button>
        </Form>
      </div>
    )
```

It doesn't validate correctly since I believe its just flat values, my state.model looks like this
```
Object {name: Object, colorId: Object}
colorId: Object
id: 2
name: "red"
```

If I use a normal select I get this:
```
Object {name: Object, colorId: 1}
```

**Comment by jquense** [comment]
The `value` of the dropdown list is that entire object: `{ id: 0, name: 'orange'}` whereas the schema is only looking for the `id` field. `valueField` tells the dropdown list what property is the `value` (and in this case you don't even need it) but the Form is completely agnostic about how the inputs work.

You can give it a hint though with the `mapValue` prop on the Field: http://jquense.github.io/react-formal/docs/#/api/field

```js
<Form.Field 
  name='colorId'
  type='dropdownlist'
  mapValue={ value => value.id }
  textField='name'
  data={ colors }
/>
```

**Comment by deezahyn** [comment]
that works!!

```
<Form.Field type={ DropdownList }
              valueField='id'
              textField='name'
              mapValue={ value => value.id }
              defaultValue={ 0 }
              data={ colors }
              name='colorId'
            />
```

>defaultValue won't work in this case because the field is manually setting value/onChange on the inputs, To set an initial value for a field initialize the form value:

Final code, its worth mentioning that the defaultValue works in this instance.

---

Lastly I can see that the errors indeed is working using the code below. however It doesn't have a map what kind of error.  say if its a type error, required error or a max error.

```

setErrors(errors) {
  if ( errors['dateOfBirth'] ) //if dob is in the error state change the message
    errors['dateOfBirth'] = "swap out the message for this one!"

  this.setState({ errors })
}
```

So the errors are just flat array without key values of what type of error it is?

**Comment by deezahyn** [comment]
Another follow up question, does react widget default to normal select and datepicker for mobile?  Or do I have to set that one up?  The reason for going with native is that the Datepicker for example is more friendly in mobile than its desktop counterpart.

**Comment by jquense** [comment]
> So the errors are just flat array without key values of what type of error it is?

yeah, it's a simple interface. Again if you need to set specific error messages, the schema object is really the place to do that.

> does react widget default to normal select and datepicker for mobile? Or do I have to set that one up? 

nope, react-widgets doesn't have any special behavior on mobile, if you want to adjust it tho it wouldn't be too difficult

```js
var DateTimePicker = require('react-widgets/lib/DateTimePicker');
var NativePicker = require('react-formal/lib/inputs/Date')

class ResponsiveDatePicker extends React.Component {
  render(){
    var Component = isMobile ? NativePicker : DateTimePicker

    return <Component {...this.props}/>
  }
}

// to set it for all date types
Form.addInputTypes('date', ResponsiveDatePicker)

// or for a single Field
<Form.Field type={ResponsiveDatePicker}/>
```

**Comment by deezahyn** [comment]
I guess that's everything, I'll report some more if I found a bug.  Any chance you can do an npm publish to include my PR #1 ?
