### ISSUE TITLE
Checking if validation errors present?

### ISSUE THREAD

**Issue by orokos** [jquense/react-formal#32]
Trying to migrate to react-formal and going rather smoothly except for one part.

We have React TransitionGroups for our error and help messages on the inputs. I used to have a way to determine a boolean hasError in my form group component which composed the label, input, and message spans. I can't seem to figure out how I can determine a hasError state inside the render of my form component? I have the Form.Message in there but it always has the root span component even if there are no errors, so it does not trigger any transitions.

I would like to conditionally include the Form.Message component only when it has messages, how can I achieve that? I would like to avoid having to pass the form's onError result back down to each input form group and determine their current state, would be a lot of ugly binding and there should be another way.

Maybe will have to write my own component instead of using Form.Message, and expose it myself?

Thanks.

**Comment by jquense** [comment]
Yeah unfortunately its not the simpliest to just drop into the the Form context for getting error messages. But you do have a few options.

1. control the `errors` prop at the top level form and pass down the `errors` as props to anything that needs them

2. As you suggest hook build a custom Message component that subscribes to a subset of errors. You can could use the HoC from `react-input-message` ('react-input-message/connectToMessageContainer') which makes it fairly straight forward, or if you don't want to worry about digging into another dep, just asking for the `context` specifically which looks sometihng like this:

```js
  contextTypes: {
    messageContainer: React.PropTypes.object
  },

  componentWillMount() {
    let container = this.context.messageContainer;

    this.unsubscribe = container.subscribe(getMessages => {
      // when errors are updated this will be called.
      // pass `getMessages` a string (or array of str) path to get a subset of errors
      // or just call it with nothing to get all the form errors
      this.setState(getMessages(this.props.for))
    })
  },

  componentWillUnmount() {
    this.unsubscribe()
  },
```

**Comment by orokos** [comment]
Went with the second one, cheers!

```
  componentWillMount() {
    this._unsubscribe = this.context.messageContainer.subscribe((getMessages) => {
      let hasError = Object.keys(getMessages(this.props.name)).length > 0;
      if (this.state.hasError != hasError) {
        this.setState({hasError});
      }
    });
  }
```

**Comment by jquense** [comment]
glad to help :)
