### ISSUE TITLE
Typing into a controlled text input causes cursor to go to the end of the field

### ISSUE THREAD

**Issue by saikat** [jquense/react-formal#33]
This can be reproduced on http://jquense.github.io/react-formal/docs/#/api?_k=y0l2ks.  Try typing in "Test" into name, then putting the cursor at "e" and typing anything. The cursor types in the e but then jumps to the end of the text input.

**Comment by jquense** [comment]
So this one seems to affect uncontrolled forms (something with an `defaultValue` and no `onChange`) is that your experience as well?

**Comment by jquense** [comment]
https://github.com/facebook/react/issues/5952

**Comment by saikat** [comment]
Yes, that's been my experience (though the presence of a defaultValue hasn't seemed to actually affect it).

**Comment by saikat** [comment]
I just tried with latest master but am still seeing this issue, by the way.

**Comment by jquense** [comment]
that's most likely because it also depends on an unreleased change in the Topeka dependency

**Comment by jquense** [comment]
I've released the fix, You can see from the docs at least that its no longer reproducable. Hopefull the same for your code :)

**Comment by LoicUV** [comment]
Having the same issue with react-bootstrap's `FormControl` in a controlled `Form`.

**Comment by rclai** [comment]
I'm using a controlled `Form` for this and the cursor is still jumping to the end, which is really bizarre.

```jsx
<Form
  value={this.state.formValue}
  schema={someSchema}
  onChange=((formValue) => this.setState({ formValue }))
>
  <Form.Field name="field1" />
</Form>
```

I'm using React 15.4.1.

**Comment by LoicUV** [comment]
For anyone still coming here, the cursor issue I had was due to the fact that my form was in a portal component (react-bootstrap's `<Overlay />`), and react has trouble maintaining cursor position for inputs in such components. cc https://github.com/react-bootstrap/react-bootstrap/issues/2323
