### ISSUE TITLE
Notify on invalid submit, pass validated result (potentially transformed) to valid submit?

### ISSUE THREAD

**Issue by orokos** [jquense/react-formal#34]
Me again! Sorry, trying to port from our old form framework to yours. :+1: 

Looking at some hacks to do this but it is looking pretty ugly, and I think this one is a fix.

Your current Form submit():
```javascript
    schema
      .validate(value, options)
      .then(() => this.notify('onSubmit', value))
      .catch(err => {
        var errors = errToJSON(err)

        if (debug && process.env.NODE_ENV !== 'production') {
          warning(!Object.keys(errors).length, '[react-formal] (onSubmit) invalid fields: ' +
            Object.keys(errors).join(', '))
        }

        this.notify('onError', errors)
      })
```

suggested:
```javascript
    schema
      .validate(value, options)
      .then((validatedValue) => this.notify('onSubmit', validatedValue))
      .catch(err => {
        var errors = errToJSON(err)

        if (debug && process.env.NODE_ENV !== 'production') {
          warning(!Object.keys(errors).length, '[react-formal] (onSubmit) invalid fields: ' +
            Object.keys(errors).join(', '))
        }

        this.notify('onError', errors)
        this.notify('onInvalidSubmit', errors)
      })
```

Returning the validatedValue should be the correct thing here, right? onSubmit should have our cleaned and validated, currently it does not and so we have to run the data through the validator again to get the proper data. If someone does not notice and do that then they might get bad data that they expect to be valid (e.g. if you use string().trim().max(100) right now it will call onSubmit saying the data is valid but it might be a string with 10 alpha characters and 5000 spaces).

I don't believe onSubmit should ever receive the raw data unless noValidate is set, which is fine then. This should be a fix as either I get unexpected data or I have an unnecessary performance hit.

Our previous framework had a way to detect an invalid submit, so when you submit the form it will run the validation as you do currently but if it fails it will call our onInvalidSubmit handler. We popup a toast telling them there is an error and scroll to the first error. We have some longer forms that we need to keep this feature for, and a notification would assist. Otherwise I need to somehow know that you are submitting, and am currently hacking into your Form to wrap the submit() with a state update, and it is not turning out so hot.

Thanks again.

**Comment by jquense** [comment]
I am honestly surprised that it doesn't pass the validated value...that is certainly the intent.

I'm fine adding an onInvalidSubmit event since its additive. If you want to PR something I'll accept it

**Comment by orokos** [comment]
PR made #35
