### ISSUE TITLE
integration with react-bootstrap

### ISSUE THREAD

**Issue by itajaja** [jquense/react-formal#39]
I am having some problems trying to integrate react-formal with [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap). What I am doing, is to call `Form.addInputTypes` with a wrapper input that looks more or less like this:

```js
render() {
    return (
      <Input
        {...this.props}
        hasFeedback={validationState != null}
        bsStyle={validationState}
        className={styles.input}
        tagName={BsInput}
      />
    );
  }
```

where `Input` comes from `react-formal/lib/inputs/Input` and `BsInput` is the react-bootstrap Input component. This works as expected, the problem is with checkboxes and the other kinds of input that don't expose a `tagName` prop, so I can't use the same approach. Is there an easier approach I am missing or do you think it makes sense to add the tagName prop also to the other input types? If that's the case, I can work on a PR.
Thanks for the great work!

**Comment by jquense** [comment]
Hi, sorry for the delay, you don't need to use the Input (from `react-formal/lib/inputs/Input`) component for custom Inputs, as long as the component takes `value` and fires `onChange` just use the component itself.

```
render() {
    return (
      <BsInput
        {...this.props}
        hasFeedback={validationState != null}
        bsStyle={validationState}
        className={styles.input}
      />
    );
  }
```

**Comment by itajaja** [comment]
Hi! Yes, I agree with you, but it would be nice to reuse some of the logic in [these files](https://github.com/jquense/react-formal/tree/master/src/inputs). Like what you have for Number or Date. Having said that, I can definitely write my own. My question is, do you think makes sense to offer that logic you implemented in the inputs? Not a huge deal, right now I am going with the approach you highlighed :)

**Comment by jquense** [comment]
Ahh right, sorry I should have remembered the RB inputs don't do any casting/coearcion. 

Yeah if adding a `component` or `tagName` props to the other inputs fixes this for the other types, then by all means lets add that to save some code rewriting. Care to PR it?

**Comment by itajaja** [comment]
I'll do that over the weekend. I'll also write some documentation. The only drawback from a design standpoint is that now there are multiple ways to write custom components, which might be confusing.

**Comment by taion** [comment]
BTW, I rewrote the inputs and form controls in React-Bootstrap.

**Comment by datapimp** [comment]
@taion so are react-formal and react-bootstrap working together? I noticed the PR in the issue you referenced is on the `next` branch of react-bootstrap .

**Comment by taion** [comment]
You need to wrap stuff up a bit. The input components are better exposed in React Formal now.

**Comment by LoicUV** [comment]
I'm having a hard time getting it to work with RB form controls. I'm also trying to use it as a controlled form. I don't know where I'm doing something wrong. The form's onChange isn't called on input change/blur/focus/submit, and the Form.Message also doesn't appear.
Here's how I integrated both : 

I have a custom component that wraps react-formal's `<Form>`, let's call it `<MyForm>` : 
```
Form.addInputTypes({text: MyInput});
// not sure if I should put MyInput or FormControl here,
// or if it's even required to use this for custom fields?
(...)
render() {
    const {children, onValidSubmit, ...rest} = this.props;
    return (
        <Form
            submit={onValidSubmit}
            {...rest}
        >
            {children}
        </Form>
    )
}
```

Then I have a custom component that wraps react-bootstrap's `<FormGroup>`, `<FormControl>`, `<ControlLabel>`, `<HelpBlock>`, and react-formal's `<Form.Message>`, let's call it `<MyInput>` : 
```
render() {
    const {children, helpBlock, id, isRequired, label,
           name, onChange, placeholder, type, value, ...rest} = this.props;
    return (
        <FormGroup
            controlId={id}
            className={isRequired ? 'required' : null}
            validationState={/* somehow get it with <Form.Trigger> ? */}
        >
            {label && <ControlLabel>{label}</ControlLabel>}
            <FormControl
                componentClass={type}
                {...rest}
                name={name}
                onChange={onChange}
                placeholder={placeholder}
                value={value}
            >
                {children}
            </FormControl>
            {helpBlock && <HelpBlock>{helpBlock}</HelpBlock>}
            <Form.Message for={name} component={HelpBlock} errorClass="has-error" />
        </FormGroup>
    );
}
```

Then when rendering the form : 
```
const formSchema = yup.object({
    firstName : yup.string().required('required')
});
<MyForm
    id="some-id"
    schema={formSchema}
    value={{firstName : this.state.firstName}}
    onChange={this.onFormChange}
    onValidSubmit={this.onFormValidSubmit}
    onInvalidSubmit={this.onFormInvalidSubmit}
>
    <MyInput
        label={"Enter your first name"}
        id="first-name"
        name="firstName"
        placeholder="John"
        isRequired
        autoFocus
    />
    <Button type="submit">submit</Button>
</MyForm>
```
react-formal@0.20.2 & react-bootstrap@0.30.2

Thanks for any insight and sorry for the trouble 😄

**Comment by A11oW** [comment]
I am some problem with wrap react-bootstrap input. I do this:
```
import FormControl from 'react-bootstrap/lib/FormControl';
import Form from 'react-formal';
import yup from 'yup';

const modelSchema = yup.object({
  minCreditSum: yup.number().required('Please input value'),
});

function MyNumberField({ value, ...props }) {
  console.log('Proxy!', value);
  return <FormControl value={value} {...props} />;
}

Form.addInputTypes('number', MyNumberField);

export default class SomeCompoennt extends React.Component {

  render () {
    return (
      <Form>
        <Form.Field
          name="minCreditSum"
          type="number"
       />
      <Form/>
    );
  }
}
```

When I change the input, "value" in MyNumberField component is equal to proxy
![2016-08-24 20 06 34](https://cloud.githubusercontent.com/assets/4760284/17940158/797c39f2-6a36-11e6-9d8a-935f0099d472.png)

What I do wrong?

**Comment by jquense** [comment]
@A11oW that is done by React to wrap the object and give better warnings. if you access any property like it was the normal event it will work.

**Comment by A11oW** [comment]
In this case React displayed an error message:
`The specified value "[object Object]" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?`
If I use default `Form.Field` all work fine.
