### ISSUE TITLE
example doc for time doesn't work

### ISSUE THREAD

**Issue by thisguychris** [jquense/react-formal#4]
On doc example: 
http://jquense.github.io/react-formal/docs/#/api/field

```javascript
<Form noValidate schema={modelSchema}>
  Use the schema to determine type
  <Form.Field 
    name='dateOfBirth' 
    placeholder='date'/>

  Override it!
  <Form.Field name='dateOfBirth' 
      type='time' 
      placeholder='time only'/>

  Use a custom Component 
  (need native 'datetime' support to see it)
  <Form.Field 
    name='dateOfBirth' 
    type={MyDateInput}/>

</Form>
```

Given that code, it seems its throwing an error
`Uncaught TypeError: Cannot read property 'dateOfBirth' of undefined`

**Comment by jquense** [comment]
yeah I forgot to fix it, thanks for the reminder.  you can just add `defaultValue={modelSchema.default()} ` to get it to work

**Comment by deezahyn** [comment]
thanks, would you mind bumping and releasing in npm -- the current master branch? I'm getting an error without the PR #1 merged.
