### ISSUE TITLE
Radio inputs

### ISSUE THREAD

**Issue by darkadept** [jquense/react-formal#42]
The docs don't seem to have examples for radio inputs and looking at the code it doesn't seem to look for type="radio". Is there a way to implement radio selects?

**Comment by jquense** [comment]
There isn't a built in Input for handling Radio lists but if you use use somethnig like the [SelectList](http://jquense.github.io/react-widgets/docs/#/selectlist) from react-widgets, if you are already using `react-formal-inputs` just specify the type as `'selectlist'`
