### ISSUE TITLE
Add class to modified input field

### ISSUE THREAD

**Issue by purplecones** [jquense/react-formal#45]
If I have a input field that has a defaultValue, is it possible to attach a class to it if the value differs from the defaultValue? A use case for this would be to highlight fields that are changed in orange so that user knows which fields they updated.

**Comment by jquense** [comment]
There isn't an API for that behavior but you can do it using the general approach of toggling a className in React. Use `value` and `onChange` on the form and then pass the updated form value down to the input where you can check if it matches the whatever your default value is, and add a class.
