### ISSUE TITLE
Accept functions as children to <Form.Message>

### ISSUE THREAD

**Issue by taion** [jquense/react-formal#46]
For handling i18n (with React Intl), I think I want to make the messages in my schema definition just be tokens, then in `<Form.Message>` resolve them to the localized strings. Something like:

```js
<Form.Message>
  {key => <FormattedMessage {...messages[key]} />}
</Form.Message>
```

It seems like accepting functions as children here would be a generic way to accomplish this.

**Comment by jquense** [comment]
That seems reasonable tho it may be a bit more complicated since Message may be passed more than one error. Why not just use the localized strings in the schema tho?

**Comment by taion** [comment]
It doesn't work nicely with react-intl, unless I define the schema in a React context. The internationalized messages are only available via `this.context.intl`.

I think ideally I'd like to be able to statically define the schemas. I suppose I could make schemas be generated from functions that take the i18n context, but that seems like a lot of book-keeping.

**Comment by taion** [comment]
Actually already supported: https://github.com/jquense/react-formal/blob/master/src/ValidationMessage.jsx#L32.
