### ISSUE TITLE
Unexpected token ILLEGAL when accessing deeply nested fields

### ISSUE THREAD

**Issue by neilff** [jquense/react-formal#48]
I have a bunch of values on an object which are fairly deep, my structure looks like this:
```
{
  "roles": {
    "57randomid": {
      create: true,
      update: false,
      delete: false,
      read: true,
    }
  }  
}
```

When I map over my fields to generate check boxes for each of these values:

```
  <ul>
    {
      Object.keys(modelSchema.fields.roles.fields).map((i) => {
        return (
          <li key={ i }>
            {
              Object.keys(modelSchema.fields.roles.fields[i].fields).map((b, idx) => {
                return (
                  <div key={ idx }>
                    <Label>
                      <Form.Field
                        type="checkbox"
                        name={ `roles.${ i }.${ b }` } />
                      <span>{ b }</span>
                    </Label>
                  </div>
                );
              })
            }
          </li>
        );
      })
    }
  </ul>
```

I am getting the following error:

```
Uncaught SyntaxError: Unexpected token ILLEGAL
```

Which points to this line here: https://github.com/jquense/react-formal/blob/0fc7eb580ed15ba58ce9d10be6e86ec0e8f43d61/lib/Form.js#L318

It appears the `getter` function is failing when it is passed something like `roles.57randomid.create`. Is it not possible to have deeply nested form fields as I have created?

**Comment by neilff** [comment]
Ah, it is getting tripped up on the property I am using, changing the `name` property to be `roles['57randomid']['create']` fixed the issue. It might be nice to have an example of accessing deeply nested values in the docs.

**Comment by jquense** [comment]
fair enough, in general tho the rule is just accessing like you would in JS, so you need brackets around the right things.
