### ISSUE TITLE
How to manually submit the Form outside?

### ISSUE THREAD

**Issue by mewben** [jquense/react-formal#49]
I have a button outside the `<Form>`. Is it possible to submit the form from there? Thanks for this by the way...

**Comment by jquense** [comment]
hi there, you can use Form.Context to wrap both the form and the button to wire them up, or you can set a ref on the Form and call it's submit() method, and finally you could control the value and error state of the form from the parent and validate against your schema manually on click passing the errors back to the form

**Comment by mewben** [comment]
Thanks for the quick reply. Got it..
