### ISSUE TITLE
I'm getting unknown property for 'for' found in eslint

### ISSUE THREAD

**Issue by deezahyn** [jquense/react-formal#5]
Since for is an html attribute I suggest using a different word since this is supposed to be a prop tying to the error message, maybe ref?

**Comment by jquense** [comment]
ref is a reserved word so that doesn't work. `for` is actually safe and doesn't conflict because in React the html attribute: for is `htmlFor` so no problems :) 

I am not sure why eslint would complain tho...

**Comment by deezahyn** [comment]
The error is coming from react-plugin of eslint:
https://github.com/yannickcr/eslint-plugin-react/issues/70

>The no-unknown-property rule handle this. This also warn you for the other HTML attributes that are different in JSX (like for -> htmlFor, colspan -> colSpan, etc.).

So if I make another suggestion, how about `errorFor` ?

**Comment by jquense** [comment]
unfortunately it doesn't make sense for me to make breaking change to an API that I think is appropriate to fix a warning in a third party eslint plugin. In any case, this error by the plugin is really a bug in their linting rule, not in my prop name choice. 'For'  is a completely valid prop name for composite components, and the plugin is casting too wide a net in an attempt to give warnings. it should only warn when you try and set 'for' on an html element, not any react component.  for what it's worth React already warns about this correctly. I would suggest raising an issue with the plugin to see if they can fix it.
