### ISSUE TITLE
How to focus React.Field?

### ISSUE THREAD

**Issue by mewben** [jquense/react-formal#50]
I have a modal form so I can't use `autoFocus`. I tried putting `ref` in `<Form.Field ref="focushere" name="name" />` and invoked `this.refs.focushere.focus()` after opening the modal but it throws this error:
```
Uncaught TypeError: _this.refs.focushere.focus is not a function
```

Please help. Thanks.

**Comment by jquense** [comment]
I'm not sure why you couldn't use autoFocus in a modal, it should work fine in that situation... in any case the ref is the form field instance, not the underlying input or widget. to get that instant e you can call inputInstance() on the ref to get the inner reference

**Comment by mewben** [comment]
It didn't work with `inputInstance()`. Maybe I was doing this wrong:

```js
this.refs.focushere.inputInstance().focus();
```

However, I found a solution using this:

```js
findDOMNode(this.refs.focushere).focus();
```

Thanks for the quick reply.
