### ISSUE TITLE
Controlled input warning

### ISSUE THREAD

**Issue by web2style** [jquense/react-formal#53]
I get the following warning when I use `react-formal`:

```
warning.js:44 Warning: Input is changing a uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
```

I'm not totally sure, but it seems to me it appeared after upgrading the project to react v15.
Is there a way to get rid of it?

**Comment by jquense** [comment]
that's coming from react itself, check the react 25 release notes. but essentially don't switch input values from undefined (uncontrolled) to something else (controlled)

**Comment by jamesjjk** [comment]
@jquense Hi jquense I understand that we would not want to switch from uncontrolled to controlled, however our form is controlled i.e. the form has an value and onChange that are reading and updating the state respectively. Is react formal not setting the state on an input without any content?

**Comment by jamesjjk** [comment]
@jquense Sorry to add, this occurs when the input is initialised with an undefined value. And then is defined. This should be acceptable as a controlled input.

**Comment by jquense** [comment]
`undefined` _means_ uncontrolled, because its the same thing as not providing the prop. There isn't anything that can be done about that, there is no other way good way of signaling to an input that it is controlled or not. We could do a hasOwnProperty check for `value` but that is moving farther from how React itself considers "existing" props. For initially empty values please use `null`

**Comment by jamesjjk** [comment]
@jquense hi thanks for the response,  I appreciate that undefined is uncontrolled. However it does give a warning when using a null even though the input is controlled at that point
```
warning.js?0260:44 Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components
```
