### ISSUE TITLE
Update form value outside of Form.Field?

### ISSUE THREAD

**Issue by neilff** [jquense/react-formal#55]
Is it possible to manually update form values outside of a Form.Field context?

I have a Codemirror component that can trigger a function `onChange`, but I am unsure how to tie it into React formal. Is this currently possible? Or is there a better approach to take?

**Comment by jquense** [comment]
store the form value in the state of the parent and pass it to the Form via the `value` prop, update your state when the form fires onChange and whatever else can change the item.

**Comment by neilff** [comment]
Right, I see what you're saying, essentially setup a controlled input. Makes sense, thanks. 👍

**Comment by markuspxpx** [comment]
Doesn't work, even if you put value='aaaaaa' the input continues empty.

**Comment by sergii-zhuravel** [comment]
The same issue - cannot set value via "value" prop.

**Comment by jquense** [comment]
Value is set on the form component y'all that's the thing that controls each field .
