### ISSUE TITLE
Trigger validation check manually?

### ISSUE THREAD

**Issue by neilff** [jquense/react-formal#59]
I have a custom field which uses ACE Editor, I've got validation working with it using `Form.Summary`, it correctly appears on the submit of the form. However, because it doesn't use `Form.Field`, it doesn't trigger validation checks when the value of the model is changed. Is it possible to trigger the validation manually in my `onChange` function of the editor component?

**Comment by jquense** [comment]
you can use and validate against the schema directly, and convert the validation errors to something the form can handle (with `Form.toErrors(ValidationError)`), for this situation though that seems like you are fighting the library, I would, instead, use `Form.Field` with your editor, any reason why you can't?

**Comment by neilff** [comment]
I could probably figure out a way to use ace directly with the `Form.Field`, but I went with the simpler route and used a wrapper component that was already made, https://github.com/securingsincity/react-ace

I'll try the `Form.toErrors` approach, thanks. Feel free to close.

**Comment by jquense** [comment]
if it fires an onChange field just use that component

```js
<Form.Field
  name='text'
  type={AceEditor}
  {...editorProps
/>
```

**Comment by jquense** [comment]
otherwise you can wrap the component, all you need to do to use it with Form.Field is accept a `value` prop and fire an `onChange` callback, most components can be made compatible with a few lines of code in a wrapping component.

**Comment by neilff** [comment]
👍 Cool, thanks
