### ISSUE TITLE
Error messages are CSV

### ISSUE THREAD

**Issue by Cyval** [jquense/react-formal#64]
Hi, I'm using react-formal for a while, and I'm getting the hang of it. What concerns me, though, is what separates multiple error messages. 

Example:

I have this code : 
` let modelSchema = yup.object({ `
  `fname: validate.required('\nOops! Your first name is required.')`
   ` .min(4, 'First name must be atleast 4 characters.')`
`});`

When I submit the form with this fname field empty, the two error messages are appended to the bottom of the field, separated by comma.

Is there any way to make this like a list, or make the first validation appear?
Because when I 'touched' the field and hit the submit button, it sees two failed validation, but the `required` is the only one appropriate, since it does not contain any value (considering "" is empty, too)

Thanks . :smile:

**Comment by jquense** [comment]
take a look at the Message API, you can control how it displays and which messages it displays fairly finely
