### ISSUE TITLE
Issues testing with Enzyme

### ISSUE THREAD

**Issue by richardvenneman** [jquense/react-formal#65]
Hey,

Thanks for this great library. The clear API, yup and minimum wiring were exactly what I was looking for.

I started developing a new form, but am stuck on testing the component. While TDD'ing I started out with the assertion that it renders errors when submitting the form without values. Unfortunately my tests won't pass (while the behaviour in the browser seems correct). With [Enzyme](http://airbnb.io/enzyme/index.html) the test looks something like this:

```javascript
const wrapper = mount(<ContactMessageForm phrases={phrases} />);
wrapper.find('form').at(0).simulate('submit');
expect(wrapper.find('.validation-error').length).to.equal(3);
```

.. but it fails:

```
  1) <ContactMessageForm /> renders errors:

      AssertionError: expected 0 to equal 3
      + expected - actual

      -0
      +3
      
      at Context.<anonymous> (contactMessageFormTest.js:27:57)
```

It seems as if the event is not actually dispatched. I also tried simulating a click on the submit button.

I've been at this for hours and hope that I just missed something. I'd love to continue to use this lib but I really need some test coverage. I setup an example repository: https://github.com/richardvenneman/react-formal-enzyme-test. The tests (`npm test`) should pass.

Thanks for reading! Please let me know if I can provide any more information.

**Comment by jquense** [comment]
the general issue here is probably that validation (and therefore submission) is asynchronous, so you are looking for messages before they are actually displayed. In general I'd not structure tests like that. you can test that submission works, but testing that errors show up is more inadvertently testing the library and your schema. instead I'd verify that your schema is correct separately. and if you want to verify that the form didn't forget to include a Message, test that the Message components are there with the correct names

**Comment by web2style** [comment]
Hi @richardvenneman. Could you please share what you came up with? I'm also thinking about how to test my forms.

**Comment by richardvenneman** [comment]
@web2style sorry, I went along with not testing the component 🙈

**Comment by web2style** [comment]
@richardvenneman This is my test example:
```
it('should render 1 validation error message', (done) => {
    const renderedComponent = mount(component)
    renderedComponent.find('#password').simulate('change', { target: { value: '123456aA' } })
    renderedComponent.find('#confirmPassword').simulate('change', { target: { value: '123' } })
    setTimeout(() => {
      expect(renderedComponent.find('.validation-error').length).toEqual(1)
      done()
    }, 300)
  })
```

`setTimeout` delay is picked experimentally, the test fails with `250` and it passes with `300`.

Not an ideal one, but I find it useful, because it tests a lot of things at once: validation rules, form input wiring, dependence of one rule from another, etc.

What do you think?

**Comment by jquense** [comment]
The 250 is due to the forms `delay` prop which denounce s validations, you can set it to 0 to reduce the timeout. 

that said instead of testing for the existence of the form error I would test that onError on the form is called with the right error and end your test in that callback

**Comment by web2style** [comment]
@jquense Thanks for pointing out to `delay`.

But I found out a weird thing. With `delay={0}` this test passes:
```
it('should render 3 validation error messages', (done) => {
    const renderedComponent = mount(component)
    renderedComponent.find('#password').simulate('change', { target: { value: '123' } })
    setTimeout(() => {
      expect(renderedComponent.find('.validation-error').length).toEqual(3)
      done()
    }, 0)
  })
```
but this one doesn't:
```
it('should render 3 validation error messages', () => {
    const renderedComponent = mount(component)
    renderedComponent.find('#password').simulate('change', { target: { value: '123' } })
    expect(renderedComponent.find('.validation-error').length).toEqual(3)
  })
```

Any ideas?

**Comment by jquense** [comment]
yes it's still async, you can't avoid the timeout it's just much shorter

**Comment by web2style** [comment]
@jquense Thank you for clarification.

I found out a weird issue with this test. Yesterday it passed for me with zero timeout. And today it doesn't. When I changed timeout to `10` it passed. My colleague confirmed it doesn't pass with `0` and passes with `10`.

I suppose there’s some time for the messages to appear in the DOM, so 10ms delay helps to wait until they are there.
