### ISSUE TITLE
Passing errors to Form.Button

### ISSUE THREAD

**Issue by rosskevin** [jquense/react-formal#71]
## Goal

I'd like to auto-disable the material-ui submit button when there are existing errors on the form.  
## Possibility 1

Interpret state automatically and pass in a prop to indicate `disabled`?
## Possibility 2 (preferred)

Have `errors` passed in on the props so my custom component can optionally interpret them, the same as they are to a `Form.Field`.
## Possibility 3

Wire up errors to the `Form.Button`?  Is there a simple way to accomplish this?

**Comment by maullerz** [comment]
Why not use that behavior?

```
  handleError(errors) {
    this.setState({ errors });
  }

      <Form
        ...
        onError={this.handleError}
      >
          <FlatButton type='submit' disabled={this.state.errors}>
          ...
```

**Comment by rosskevin** [comment]
Thanks @maullerz - can do that, but I'll have to add it to every single form (and we have a lot of them)

Iit might be nice to have consistency. e.g.  the errors are already passed to the inputs as props, would be nice to get the same thing on the buttons so I can interpret them with my custom component and without the extra/repetitive code on every form.

**Comment by maullerz** [comment]
Understood. So i agree with second solution.

**Comment by LoicUV** [comment]
I'd also like the second solution. I'm using react-bootstrap (FormControl and FormGroup which handles the validationState) and have no transparent way of styling my inputs when an error occurs other than putting the errors in state for each form.

**Comment by jquense** [comment]
folks, sorry for the delay, but you can inject errors into any component via Form.Trigger which is a re-export of the react-input-message MessageTrigger

**Comment by rosskevin** [comment]
Thanks @jquense, I'm pretty lost when it comes to the trigger.  I imagine I need to wire up something like what is done in [`Field`](https://github.com/jquense/react-formal/blob/master/src/Field.jsx#L218) correct?

**Comment by jquense** [comment]
For the latest version of RF it should be fairly simple:

```jsx
function MySubmitButton(props) {
  return (
    <Form.Trigger>
      {({ messages }) => 
         <Form.Button 
             {...props}
             type='submit' 
             disabled={!!Object.keys(messages).length)
         />
      }
    </Form.Trigger>
}
```

older versions need to specify an `inject` function tho

**Comment by vendelin8** [comment]
I used the code above (with fixed typos):
    import React from 'react';
    import Form from 'react-formal';
    
    export function SubmitButton(props) {
      return (
        <Form.Trigger>
          {({ messages }) =>
             <Form.Button
                 {...props}
                 type='submit'
                 disabled={!!Object.keys(messages).length}
             />
          }
        </Form.Trigger>
      );
    }

And I got this warning in the console:

    warning.js:36 Warning: Failed prop type: A `group` prop is required when no for `prop` is providedfor component MessageTrigger
    in MessageTrigger (created by MessageListener)
    in MessageListener (at SubmitButton.js:6)
    in SubmitButton (at login.component.js:44)
    in form (created by Form)
    in MessageContainer (created by MessageListener)
    in MessageListener (created by Form)
    in BindingContext (created by Form)
    in Form (created by Uncontrolled(Form))
    in Uncontrolled(Form) (at login.component.js:32)
    in div (at login.component.js:30)
    in LoginComponent (created by RouterContext)
    in RouterContext (created by Router)
    in Router (at App.js:42)
    in div (at App.js:41)
    in div (at App.js:40)
    in div (at App.js:35)
    in App (at index.js:7)

I tried to search for it, but I found nothing.

**Comment by web2style** [comment]
@vendelin8 You can use it like this: `<Trigger group='@all'>` as stated here: https://github.com/jquense/react-input-message#messagetrigger

**Comment by vendelin8** [comment]
It's working now, thank you.
