### ISSUE TITLE
How does one supply a context object to yup.validate

### ISSUE THREAD

**Issue by basicdays** [jquense/react-formal#72]
Hey,

I have a yup schema that is using `.when` on a type, and checking a context value (e.g. a value prepended with `$`. https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema

I was wondering how I would be able to supply context information to a yup validation context with `react-formal`? I've tried putting the prop on the both the `Form` and `Form.Field` components with no luck.

**Comment by jquense** [comment]
Hey there, none form props are passed to yup, so to add context, you add a `context={{ foo: 5 }}` prop to your Form.

**Comment by basicdays** [comment]
That worked! Thanks so much. Awesome project.

**Comment by basicdays** [comment]
By the way, that doesn't look like that property is in the documentation. Hopefully this is a supported feature?

**Comment by jquense** [comment]
yup!
