### ISSUE TITLE
Field with yup.date() schema resets onBlur

### ISSUE THREAD

**Issue by trackchris** [jquense/react-formal#74]
I'm using react-formal@0.18.8 with yup@0.20.0 there appears to be an issue with 'Form.Field' when it has the yup.date() schema validation attached. If you choose any date from the picker it will appear as the form field value, but when you either click away from the field or use the keyboard to loose focus, it resets back to the 'dd/mm/yyyy' place holder.

I had this issue in a Meteor project initially and thought it was a problem linked to Meteor, but I've confirmed the same thing happens when using a plain React project with Webpack/Babel using the demo/example code from http://jquense.github.io/react-formal/docs/#/api/form?_k=o6rhng - this rules out it being an issue with my own code.

I was previously running react-formal@0.17.2 with yup@0.18.3 and had no problems whatsoever, so it appears to be something that has changed in a release since those.

I've uploaded a screen recording of the issue here - https://youtu.be/vm3JPSYobzA

Please let me know if there is any other information I can provide to help diagnose the problem, thanks!

**Comment by trackchris** [comment]
Here is what appears in the browser console when you choose a date:

<img width="555" alt="screen shot 2016-08-03 at 09 13 53" src="https://cloud.githubusercontent.com/assets/11329036/17358608/b6dec4aa-595a-11e6-9033-210e556fa5b4.png">

State object has been declared in the constructor so it's not a lack of availability there...

`constructor(props) {
    super(props);
    this.state = {};
  }`

**Comment by kenkus-futurice** [comment]
On this line:
[https://github.com/jquense/react-formal/blob/master/src/inputs/Date.jsx#L56](https://github.com/jquense/react-formal/blob/master/src/inputs/Date.jsx#L56)

This:
`parse(e.target.value, value, type)`
should be perhaps like this?:
`parse(e, value, type)`

**Comment by jquense** [comment]
I'll take a look, maybe something changed recently in how the native inputs work

**Comment by kenkus-futurice** [comment]
Great! As @trackchris noted the breaking change is basically in `react-formal@0.17.3`.

**Comment by trackchris** [comment]
Tested and can confirm the fix has solved the issue. Thanks @jquense 👍
