### ISSUE TITLE
Using 'when' for dependent fields the onChange event doesn't force a validation.

### ISSUE THREAD

**Issue by DaemonCahill** [jquense/react-formal#75]
I'm trying to use a basic example from the site:

>     name: yup.object({
>       first: defaultStr
>         .required('please enter a first name')
>         .when('last', (last, schema) => schema.min(last.length)),
> 
>       last: defaultStr
>         .required('please enter a surname'),
>     }),

In the above example, if I set the form values for first and last to "name" and "longname" respectively (and in that order), the validation on first using the 'when' structure will not validate unless I go back and change that field or try to submit the form.

Basically, I want the 'when' clause to validate first when I change last. Seems like I am missing something fundamental. Or, if not...is there a workaround for this?

Thank you for a great plugin!

**Comment by DaemonCahill** [comment]
@jquense  Upon further investigation it appears that the updatedPaths on the onChange event are the only items validated, not the entire schema?

**Comment by DaemonCahill** [comment]
@jquense Just found alsoValidates and recursive in the documentation. This appears to give me exactly what I need. Apologies for not reading fully! I'll give those a try.

**Comment by jquense** [comment]
yup `alsoValidates` is what you want. It would be nice if react-formal could know when dependent fields are changed but thats a harder then it might appear.

**Comment by DaemonCahill** [comment]
@jquense excellent, thanks!

**Comment by DaemonCahill** [comment]
@jquense sorry to bother you again but I'm running around in circles and can't understand why this doesn't work:

```
const modelSchema = yup.object({
  first:
    yup.string()
    .required()
    .when('second', (second, schema) =>
      second === 'hello' ? schema.min(5) : schema.min(0)
    ),
  second: yup.string().required(),
});
```

```
        <Form
          schema={modelSchema}
          defaultValue={modelSchema.default()}
          onSubmit={this.onSubmitButtonClick}
        >
          <Form.Field name='first' placeholder='first' />
          <Form.Field name='second' placeholder='second' alsoValidates={['first']} />

          <Form.Summary />
          <Form.Button type='submit'>Submit</Form.Button>
        </Form>
```

Very simple logic that works fine - first must be greater than 5 if second is 'hello' - but the alsoValidates does not seems to work when I change second. I have to go in and fire the change even for first to make the error message go away.

Thoughts?

Really appreciate your help!

**Comment by maullerz** [comment]
I have some similar code in my app
Try this
```
first: yup.string()
  .when('second', {
    is: 'hello',
    then: yup.string().min(5),
    otherwise: yup.string().min(1),
  }),
second: yup.string()
```

**Comment by DaemonCahill** [comment]
@maullerz Thanks! I'll try this out shortly and let you know how it goes.

**Comment by jquense** [comment]
the code for both looks good. I'll double check to make sure there isn't a regression

**Comment by DaemonCahill** [comment]
@jquense @maullerz I tried that schema as well and had the same issue with alsoValidates. Thanks for the suggestion, though!

**Comment by jquense** [comment]
oops there was a bug, should be fixed in latest.
