### ISSUE TITLE
Cannot resolve universal promise on 0.19.2

### ISSUE THREAD

**Issue by mjrussell** [jquense/react-formal#76]
After updating to the latest version, I get the following:

```
ERROR in ./~/react-formal/lib/errorManager.js
Module not found: Error: Cannot resolve module 'universal-promise' in /<my_project>/node_modules/react-formal/lib
```

**Comment by mjrussell** [comment]
`npm install --save universal-promise` works but Im confused as to why I didn't have to do this on 0.19.1.

Also would it make more sense to use babel polyfill/regenerator runtime to provide a promise library rather than your own?

**Comment by jquense** [comment]
i forgot to add the dep is why. care to send a PR?

**Comment by mjrussell** [comment]
Done, see #77. I noticed that this wasn't picked up automatically. Do you want to set up a travis integration for your tests?

**Comment by mjrussell** [comment]
Oh just kidding you have travis!
