### ISSUE TITLE
Documentation site 404's

### ISSUE THREAD

**Issue by ptsteadman** [jquense/react-formal#78]
Currently can't view the (quite helpful!) documentation site!

**Comment by jquense** [comment]
Ya looking into it. thanks for the heads up

**Comment by jquense** [comment]
ahhh the url changed without realizing it
http://jquense.github.io/react-formal/

**Comment by 4esnog** [comment]
Documentation site's link in readme is still broken. (http://jquense.github.io/react-formal/docs/#/getting-started)
Fix it, please. =)
