### ISSUE TITLE
Value formatter

### ISSUE THREAD

**Issue by kirillkostko** [jquense/react-formal#82]
I would like to format number values in the onChange callback. Is there the way to control the cursor position on the field or maybe you can suggest some other solutions for that case. Thank you in advance!

**Comment by jquense** [comment]
react-formal doesn't really have an opinion about the inputs you use, the ones provided are intentionally _very_ simple wrappers around native html inputs. If you want more nuanced or complex behavior you might want to try one of many libraries that provide form inputs (like react-widgets). You can use any component you want with react formal, either directly or with a simple wrapper.

**Comment by kirillkostko** [comment]
I've created a wrapper as you suggested. @jquense thank you for your help!
