### ISSUE TITLE
React warning: Manually Calling React.PropTypes validation function

### ISSUE THREAD

**Issue by emilyfeder** [jquense/react-formal#86]
I'm getting loads of this warning popping up when I use react-formal in my app. Not blocking, just annoying, so I wanted to put it on your radar.

```Warning: You are manually calling a React.PropTypes validation function for the `mapValue` prop on `Binding`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.```

**Comment by jquense** [comment]
delete you node_modules and upgrade to the latest version, this has been fixed for a bit now. Thanks!
