### ISSUE TITLE
incorrect doc link

### ISSUE THREAD

**Issue by bsr203** [jquense/react-formal#96]
The documentation link on the readme, at the following section, points to invalid site

```
Use

For more complete api documentations, live examples, and getting started guide check out the documentation site.

```

**Comment by maullerz** [comment]
Just send PR

**Comment by bsr203** [comment]
not sure when will I get around setting up a dev env for this. will try. thanks

**Comment by bsr203** [comment]
don't use this lib anymore, so closing.
