### ISSUE TITLE
A "valid" className when required and valid

### ISSUE THREAD

**Issue by vendelin8** [jquense/react-formal#97]
Hi,

This is a feture request.
It would be awesome to have a className for fields, that shows if the field is required and valid at the same time. Like the errorClass. Probably with the name of "validClass".

An example in angular2:
on page:
https://angular.io/docs/ts/latest/guide/forms.html
this image:
https://angular.io/resources/images/devguide/forms/hero-form-2.png

So it would show, that the input is required, but OK.

**Comment by jquense** [comment]
I'm probably not going to add an explicit valid className but Form Fields now pass through a meta prop that has the current valid or invalid state so it's easy to add yourself now!

**Comment by vendelin8** [comment]
I tried to find some information about this meta you're mentioning, but no luck. Can you show me, how can I use it?
Thanks!

**Comment by jquense** [comment]
there isn't really any documentation right now, but each Form.Field injects a prop called `meta` into the input it renders.

```js
function MyInput({ meta, ...props }) {
  const { valid, invalid, errors, schema } = meta;
  return // render an input
}

<Form.Field name='name' type={MyInput} />
```

**Comment by vendelin8** [comment]
I can't make it work.

I have this in the form:

    <Form.Field name="login" className="login" placeholder="Login name" type={ReqField}/>

and this is the Reqfield class in another file:

    import React from 'react';
    import Form from 'react-formal';

    function ReqField({ meta, ...props }) {
      const { valid, invalid, errors, schema } = meta;
      console.log(valid, invalid, errors, schema, props);
      return (
        <input {...props}/>
      )
    }

The console is empty, it doesn't get called.

**Comment by vendelin8** [comment]
Even after upgrading to react-formal 0.23.1 .
