### ISSUE TITLE
`required` determination from yup schema inside a Field component

### ISSUE THREAD

**Issue by rosskevin** [jquense/react-formal#99]
I am providing material-ui components for react-formal to render.  As part of the [material design spec for required fields](https://material.google.com/components/text-fields.html#text-fields-required-fields), I need to display an asterisk in the label.

With me so far? Great.

I'm using yup - awesome - love it.  So:

**Given** a `schema`
  ```javascript
const schema = yup.object({
  firstName: yup.string().trim().default('').required('First name is required')
})
  ```
**When** I render a custom material-ui field
**Then** I need to inspect the yup schema to determine if it is `required`

I see that I receive `meta` with the `StringSchema`:
![form_-_dummy_com](https://cloud.githubusercontent.com/assets/136564/20363636/99bdee3e-ac05-11e6-8e02-ef6bc7a19011.png)

I didn't spot anything in the [yup api](https://github.com/jquense/yup), can I query the `StringSchema` somehow to determine `required`?

**Comment by jquense** [comment]
try: https://github.com/jquense/yup#mixeddescribe-schemadescription,

it should give you a list of the schema tests (among other things)

**Comment by rosskevin** [comment]
Thanks Jason!
![form_-_dummy_com](https://cloud.githubusercontent.com/assets/136564/20363969/fa91aab0-ac06-11e6-9463-132c63241c6b.png)
